jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
    displayName: 'Install Node.js'
  - script: |
      npm install -g newman newman-reporter-htmlextra
      echo Running Newman tests...
      newman run /TrelloAPI/Trello_API_Tests.postman_collection.json --environment /TrelloAPI/UAT.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export /TrelloAPI/Reports/report.html --verbose
      echo Newman tests completed.
    displayName: 'Run Newman tests with HTMLExtra reporter'