jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
    displayName: 'Install Node.js'
  - script: |
      echo Running NPM login...
      npm login
    displayName: 'NPM Login'
  - script: |
      echo Installing newman globally...
      npm install -g newman
      echo Installing completed.
    displayName: 'Install Newman'
  - script: |
      echo Installing newman-reporter-xml globally...
      npm install -g newman-reporter-xml
      echo Installing completed.
    displayName: 'Install Newman XML Reporter'
  - script: |
      echo Running NPM logout...
      npm logout
    displayName: 'NPM Logout'
  - script: |
      echo Running Newman tests...
      newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,xml --reporter-xml-export "C:\agents\_work\2\s\TrelloAPI\TestResults\result.xml" --verbose 2>&1
      echo Newman tests completed.
    displayName: 'Run Newman tests with XML reporter'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true
      testRunTitle: 'Postman Tests'
