jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
      checkLatest: true
    displayName: 'Install Node.js'
  - script: |
      echo Installing newman globally...
      npm install -g newman
      echo Installing completed.
    displayName: 'Install Newman'
  - script: |
      echo Installing newman-reporter-junit globally...
      npm install -g newman-reporter-junit
      echo Installing completed.
    displayName: 'Install Newman JUnit Reporter'
  - task: CmdLine@2
    inputs:
      script: 'newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,htmlextra,junit --reporter-junit-export "C:\agents\_work\2\s\TrelloAPI\report.xml" --verbose'
    displayName: 'Run Newman tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '/TrelloAPI/report.xml'
      failTaskOnFailedTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()
