jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
    displayName: 'Install Node.js'
  - script: |
      echo Running Newman tests...
      newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export "C:\agents\_work\2\s\TrelloAPI\TestResults\result.xml" --verbose 2>&1
      echo Newman tests completed.
    displayName: 'Run Newman tests with HTMLExtra reporter'
  - task: CmdLine@2
    inputs:
      script: |
        echo Running npm logout...
        npm logout
        echo Npm logout completed.

        echo Running npm login...
        npm login
        echo Npm login completed.

        echo Installing Newman XML Reporter...
        npm install -g newman-reporter-xml
        echo Newman XML Reporter installation completed.
    displayName: 'Install Newman XML Reporter'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true
      testRunTitle: 'Postman Tests'
