jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
    displayName: 'Install Node.js'
  - script: |
      echo Installing newman...
      npm install -g newman newman-reporter-htmlextra newman-reporter-json
      echo Installing completed.
      echo Running Newman tests...
      newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,htmlextra,json --reporter-json-export "C:\agents\_work\2\s\TrelloAPI\report.json" --verbose
      echo Newman tests completed.
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JSON'
      testResultsFiles: '/TrelloAPI/report.json'
      failTaskOnFailedTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()
