jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: CmdLine@2
    inputs:
      script: '
      newman --version
      newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export "C:\agents\_work\2\s\TrelloAPI\report.html" --verbose'
    displayName: 'Run Newman tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '/TrelloAPI/report.html'
      failTaskOnFailedTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()
