jobs:
- job: RunPostmanTests
  displayName: 'Run Postman Tests'
  pool:
    name: Pool02
    demands:
    - Agent.Name -equals vm04
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Specify the desired Node.js version
    displayName: 'Install Node.js'
  - script: |
      echo Installing newman...
      npm install -g newman newman-reporter-htmlextra newman-reporter-xml
      echo Installing completed.
      echo Running Newman tests...
      newman run "C:\agents\_work\2\s\TrelloAPI\Trello_API_Tests.postman_collection.json" --environment "C:\agents\_work\2\s\TrelloAPI\UAT.postman_environment.json" --reporters cli,htmlextra,xml --reporter-xml-export "C:\agents\_work\2\s\TrelloAPI\report.xml" --verbose
      echo Newman tests completed.
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Convert XML to JUnit format using XSLT transformation
        $xsltPath = "$(Agent.WorkFolder)\xslt\newman-to-junit.xslt"
        $xmlPath = "$(Agent.WorkFolder)\TrelloAPI\report.xml"
